HTTP/1.0 408 Request Time-out
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Error</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <style>
        body {
          font-family: "HelveticaNeue-Light", "Segoe UI", "Roboto Light", sans-serif;
          color: #6A7A82;
        }
        .wrapper {
          width: 600px;
          margin: 0 auto;
          text-align: center;
        }
        .logo {
          position: absolute;
          top: 20px;
          left: 20px;
        }
        .error {
          position: absolute;
          right: 20px;
          top: 20px;
        }
        h1 {
          margin-top: 40%;
          margin-bottom: 5%;
        }
        strong {
          font-weight: 400;
        }
        .text {
          line-height: 1.25;
        }
        </style>
    </head>
    <body>
        <div class="wrapper">
        <div class="error">Error: 408 Request Time-out</div>
        <div class="logo">
        <svg version="1.1" id="logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="200px" height="50px" viewBox="0 0 1220 300" enable-background="new 0 0 1220 332.414" xml:space="preserve">
    <g>
        <linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="340.8057" y1="85.4277" x2="355.834" y2="85.4277">
            <stop offset="0.0108" style="stop-color:#1F293E" />
            <stop offset="1" style="stop-color:#2F3A4F" />
        </linearGradient>
        <polygon fill="url(#SVGID_1_)" points="340.806,48.94 342.911,87.257 355.834,121.916 348.564,56.87   " />
        <linearGradient id="SVGID_2_" gradientUnits="userSpaceOnUse" x1="177.2173" y1="79.5903" x2="234.8232" y2="79.5903">
            <stop offset="0.0108" style="stop-color:#1F293E" />
            <stop offset="1" style="stop-color:#2F3A4F" />
        </linearGradient>
        <polygon fill="url(#SVGID_2_)" points="234.823,51.356 210.401,88.253 177.217,107.824 203.676,70.569     " />
        <linearGradient id="SVGID_3_" gradientUnits="userSpaceOnUse" x1="177.2173" y1="118.9526" x2="196.1392" y2="118.9526">
            <stop offset="0.0108" style="stop-color:#1F293E" />
            <stop offset="1" style="stop-color:#2F3A4F" />
        </linearGradient>
        <polygon fill="url(#SVGID_3_)" points="177.217,107.824 183.002,123.374 196.139,130.082 191.969,117.396  " />
        <linearGradient id="SVGID_4_" gradientUnits="userSpaceOnUse" x1="180.4463" y1="177.4526" x2="190.7236" y2="177.4526">
            <stop offset="0.0108" style="stop-color:#1F293E" />
            <stop offset="1" style="stop-color:#2F3A4F" />
        </linearGradient>
        <polygon fill="url(#SVGID_4_)" points="188.654,166.458 180.446,176.521 184.129,188.447 190.724,177.012  " />
        <linearGradient id="SVGID_5_" gradientUnits="userSpaceOnUse" x1="297.7637" y1="165.4878" x2="335.7832" y2="165.4878">
            <stop offset="0.0108" style="stop-color:#1F293E" />
            <stop offset="1" style="stop-color:#2F3A4F" />
        </linearGradient>
        <polygon fill="url(#SVGID_5_)" points="335.783,154.455 301.812,163.312 297.764,176.521 334.725,156.173  " />
        <linearGradient id="SVGID_6_" gradientUnits="userSpaceOnUse" x1="297.7637" y1="197.2437" x2="345.4326" y2="197.2437">
            <stop offset="0.0108" style="stop-color:#1F293E" />
            <stop offset="1" style="stop-color:#2F3A4F" />
        </linearGradient>
        <polygon fill="url(#SVGID_6_)" points="297.764,176.521 331.353,200.095 345.433,217.966 324.479,206.821  " />
        <linearGradient id="SVGID_7_" gradientUnits="userSpaceOnUse" x1="333.9443" y1="240.2642" x2="345.4326" y2="240.2642">
            <stop offset="0.0108" style="stop-color:#1F293E" />
            <stop offset="1" style="stop-color:#2F3A4F" />
        </linearGradient>
        <polygon fill="url(#SVGID_7_)" points="345.433,217.966 333.944,236.71 337.374,262.562 345.433,232.975   " />
        <g>
            <g>
                <polygon fill="none" points="79.577,128.681 59.472,96.054 48.241,126.896            " />
                <polygon fill="none" points="76.741,48.627 135.939,49.978 94.448,0          " />
                <polygon fill="none" points="215.621,101.359 176.946,158.38 215.621,158.805 254.296,158.38          " />
                <polygon fill="none" points="157.207,133.103 142.196,132.248 149.471,140.488            " />
                <polygon fill="none" points="170.311,91.379 170.988,79.155 159.808,78.729           " />
            </g>
            <g>
                <polygon fill="none" points="215.621,136.368 253.589,157.338 231.407,124.634            " />
                <polygon fill="none" points="294.451,179.907 288.321,176.521 290.329,180.544            " />
            </g>
        </g>
        <g>
            <polygon fill="none" points="173.621,159.311 188.835,165.576 196.139,130.083 176.946,158.38         " />
            <polygon fill="none" points="331.353,295.882 354.488,299.738 337.374,262.562        " />
            <line fill="none" x1="355.834" y1="121.916" x2="335.783" y2="154.455" />
            <polygon fill="none" points="345.433,217.966 345.433,217.966 345.433,217.966        " />
            <polygon fill="none" points="234.823,51.356 234.823,51.356 234.823,51.356       " />
        </g>
        <linearGradient id="SVGID_8_" gradientUnits="userSpaceOnUse" x1="52.5176" y1="70.4839" x2="69.7592" y2="53.2423">
            <stop offset="0" style="stop-color:#8AB93F" />
            <stop offset="0.6774" style="stop-color:#A9D153" />
        </linearGradient>
        <polygon fill="url(#SVGID_8_)" points="54.703,64.925 29.586,47.552 62.769,57.953 92.69,76.173   " />
        <linearGradient id="SVGID_9_" gradientUnits="userSpaceOnUse" x1="387.5723" y1="71.9478" x2="352.6369" y2="51.7778">
            <stop offset="0.0108" style="stop-color:#1F293E" />
            <stop offset="1" style="stop-color:#2F3A4F" />
        </linearGradient>
        <polygon fill="url(#SVGID_9_)" points="401.656,47.552 358.491,60.824 338.552,76.173 386.792,60.14   " />
        <g>
            <linearGradient id="SVGID_10_" gradientUnits="userSpaceOnUse" x1="122.603" y1="47.5522" x2="122.603" y2="317.5527">
                <stop offset="0" style="stop-color:#8AB93F" />
                <stop offset="0.6774" style="stop-color:#A9D153" />
            </linearGradient>
            <polygon fill="url(#SVGID_10_)" points="170.988,79.155 191.146,79.922 205.068,52.035 215.621,51.794 172.56,50.812
            135.939,49.978 76.741,48.627 29.586,47.552 92.69,76.173 159.808,78.729      " />
            <polyline fill="none" points="92.69,76.173 142.196,132.248 149.471,140.488 149.862,140.931 68.552,317.552 89.279,197.943
            96.518,156.173 79.577,128.681 59.472,96.054 29.586,47.552       " />
            <linearGradient id="SVGID_11_" gradientUnits="userSpaceOnUse" x1="-8.689" y1="240.312" x2="124.0696" y2="107.5534">
                <stop offset="0" style="stop-color:#8AB93F" />
                <stop offset="0.6774" style="stop-color:#A9D153" />
            </linearGradient>
            <polygon fill="url(#SVGID_11_)" points="59.472,96.054 79.577,128.681 96.518,156.173 89.279,197.943 68.552,317.552
            149.862,140.931 149.471,140.488 142.196,132.248 92.69,76.173 29.586,47.552      " />
        </g>
        <g>
            <linearGradient id="SVGID_12_" gradientUnits="userSpaceOnUse" x1="331.9775" y1="168.2407" x2="186.4776" y2="84.2364">
                <stop offset="0.0108" style="stop-color:#1F293E" />
                <stop offset="1" style="stop-color:#2F3A4F" />
            </linearGradient>
            <polygon fill="url(#SVGID_12_)" points="340.806,48.94 298.402,49.907 234.823,51.356 215.621,51.794 205.068,52.035
            191.146,79.922 126.069,210.277 184.129,188.447 215.621,176.607 188.835,165.576 173.621,159.311 176.946,158.38
            196.139,130.083 215.621,101.359 229.896,80.311 240.096,79.922 338.552,76.173 401.656,47.552         " />
            <linearGradient id="SVGID_13_" gradientUnits="userSpaceOnUse" x1="341.5176" y1="317.5522" x2="341.5176" y2="47.5527">
                <stop offset="0.0108" style="stop-color:#1F293E" />
                <stop offset="1" style="stop-color:#2F3A4F" />
            </linearGradient>
            <polygon fill="url(#SVGID_13_)" points="337.374,262.562 354.488,299.738 362.689,317.552 359.755,300.616 345.433,217.966
            334.725,156.173 335.783,154.455 355.834,121.916 401.656,47.552 338.552,76.173 281.379,140.931       " />
        </g>
        <linearGradient id="SVGID_14_" gradientUnits="userSpaceOnUse" x1="267.0293" y1="155.9268" x2="267.0293" y2="164.9672">
            <stop offset="0" style="stop-color:#8AB93F" />
            <stop offset="0.6774" style="stop-color:#A9D153" />
        </linearGradient>
        <polygon fill="url(#SVGID_14_)" points="254.296,158.38 270.236,161.437 279.762,159.375 265.24,155.927   " />
        <g>
            <linearGradient id="SVGID_15_" gradientUnits="userSpaceOnUse" x1="247.6914" y1="79.9224" x2="247.6914" y2="210.2771">
                <stop offset="0" style="stop-color:#8AB93F" />
                <stop offset="0.6774" style="stop-color:#A9D153" />
            </linearGradient>
            <polygon fill="url(#SVGID_15_)" points="254.025,107.824 240.096,79.922 229.896,80.311 215.621,101.359 231.407,124.634
            253.589,157.338 254.296,158.38 279.762,159.375      " />
            <linearGradient id="SVGID_16_" gradientUnits="userSpaceOnUse" x1="215.625" y1="79.9224" x2="215.625" y2="210.2773">
                <stop offset="0" style="stop-color:#8AB93F" />
                <stop offset="0.6774" style="stop-color:#A9D153" />
            </linearGradient>
            <polygon fill="url(#SVGID_16_)" points="215.621,176.607 215.629,176.61 215.621,176.593      " />
            <linearGradient id="SVGID_17_" gradientUnits="userSpaceOnUse" x1="-41.4863" y1="183.2871" x2="305.1728" y2="183.2871">
                <stop offset="0.7634" style="stop-color:#A9D153" />
                <stop offset="1" style="stop-color:#8AB93F" />
            </linearGradient>
            <polygon fill="url(#SVGID_17_)" points="305.173,210.277 290.329,180.544 288.321,176.521 279.762,159.375 254.296,158.38
            161.622,156.297 215.621,176.593 215.629,176.61 244.799,187.577      " />
        </g>
    </g>
    
</svg>  
</div>
<h1>Site temporary unavailable</h1>
<div class="text">There is a problem with loading this site, but we're already taking care of it! Wait for a few minutes and try refreshing the page. If it doesn't work - contact our support team.</div>
<br />
<div class="text">email: <strong>support@pqstudio.pl</strong></div>
<div class="text">tel.: <strong>882 153 932</strong></div>
</div>


    </body>
</html>
